### ISSUE TITLE
Import of YAML fails

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [javrasya/fakejira#2]
On import of the project,
after running `pip install -r requirements.txt` 
and running `python manage.py makemigrations && python manage.py migrate`
Using the following packages with Python 3.5.3

```
        "django": {
            "version": "==1.11.2"
        },
        "django-mptt": {
            "version": "==0.8.7"
        },
        "django-river": {
            "version": "==0.9.0"
        },
        "factory-boy": {
            "version": "==2.8.1"
        },
        "faker": {
            "version": "==0.7.15"
        },
        "mock": {
            "version": "==2.0.0"
        },
        "pbr": {
            "version": "==3.0.1"
        },
        "python-dateutil": {
            "version": "==2.6.0"
        },
        "pytz": {
            "version": "==2017.2"
        },
        "pyyaml": {
            "version": "==3.12"
        },
        "six": {
            "version": "==1.10.0"
        }
```

The Following errors occur:

```
System check identified some issues:

WARNINGS:
river.ProceedingMeta.groups: (fields.W340) null has no effect on ManyToManyField.
river.ProceedingMeta.parents: (fields.W340) null has no effect on ManyToManyField.
/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField User.last_login received a naive datetime (2016-05-29 13:09:07.776879) while time zone support is active.
  RuntimeWarning)
Traceback (most recent call last):
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/db/models/options.py", line 617, in get_field
    return self.fields_map[field_name]
KeyError: 'field'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/serializers/pyyaml.py", line 79, in Deserializer
    for obj in PythonDeserializer(yaml.load(stream, Loader=SafeLoader), **options):
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/serializers/python.py", line 129, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/db/models/options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: ProceedingMeta has no field named 'field'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/management/commands/loaddata.py", line 166, in load_label
    for obj in objects:
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/serializers/pyyaml.py", line 85, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/serializers/pyyaml.py", line 79, in Deserializer
    for obj in PythonDeserializer(yaml.load(stream, Loader=SafeLoader), **options):
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/core/serializers/python.py", line 129, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/home/thief/.local/share/virtualenvs/fakejira-6KbNSplp/lib/python3.5/site-packages/django/db/models/options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/thief/dev/mystic/fakejira/base/fixtures/base.yaml': ProceedingMeta has no field named 'field'

```

Any suggestions?

**Comment by HenryMehta** [comment]
'field' has been removed from the proceedingmeta model.

If you go into base.yaml and remove the rows in proceedingmeta with the field named 'field' then the load worked for me
